### Register
GET http://localhost:3000
### register
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
  "name": "yoga",
  "email": "yoga1@inmo.co.id",
  "password": "12345678"
}
### Login
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "email": "yoga1@inmo.co.id",
  "password": "12345678"
}
### Login cm4guxxi20001tufgmi9msntm
POST http://localhost:3000/api/v1/session
Content-Type: application/json

{
  "sessionId": "cm5f43lzf0002tuqodk48c3oe"
}